# Generated by Django 3.0.8 on 2020-08-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss', models.IntegerField(blank=True, null=True)),
                ('sub', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=200, null=True)),
                ('clss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pervez.Cls')),
            ],
        ),
    ]
