# Generated by Django 3.0.8 on 2020-08-04 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(blank=True, max_length=100, null=True)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pervez.Cls')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pervez.Subject'),
        ),
    ]
