# Generated by Django 3.0.8 on 2020-08-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0002_auto_20200804_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cls',
            name='sub',
        ),
    ]
