# Generated by Django 3.0.8 on 2020-08-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0003_remove_cls_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='clas',
        ),
    ]
