# Generated by Django 3.0.8 on 2020-08-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0006_questionanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clss', models.IntegerField(blank=True, choices=[(7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('sub', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], max_length=200, null=True)),
                ('chapter', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_topic', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
