# Generated by Django 3.0.8 on 2020-08-07 11:13

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0008_auto_20200806_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='vedio',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
