# Generated by Django 3.0.8 on 2020-08-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0009_questionanswer_vedio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='vedio',
        ),
    ]
