# Generated by Django 3.0.8 on 2020-08-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0010_remove_questionanswer_vedio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
