# Generated by Django 3.1 on 2020-08-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0014_auto_20200822_0744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answers',
            new_name='answer',
        ),
    ]
