# Generated by Django 3.1 on 2020-08-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0015_auto_20200822_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answer',
            new_name='answers',
        ),
    ]
