# Generated by Django 3.1 on 2020-08-22 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0017_auto_20200822_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='clss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pervez.cls'),
        ),
    ]
