# Generated by Django 3.1 on 2020-08-22 08:25

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0020_cls_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='vedio',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
