# Generated by Django 3.1 on 2020-08-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0021_auto_20200822_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='cls',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
