# Generated by Django 3.1 on 2020-08-23 05:39

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0022_cls_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('vedio', embed_video.fields.EmbedVideoField(blank=True, null=True)),
            ],
        ),
    ]
