# Generated by Django 3.1 on 2020-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0023_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_content', models.TextField(null=True)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
    ]
