# Generated by Django 3.1 on 2020-08-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0024_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.CharField(default='https://source.unsplash.com/collection/190727/1600x900', max_length=500),
        ),
    ]
