# Generated by Django 3.1 on 2020-08-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0026_remove_blogs_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lectures',
            new_name='Lecture_chapter',
        ),
    ]
