# Generated by Django 3.1 on 2020-08-25 07:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0027_auto_20200823_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='extras',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
