# Generated by Django 3.1 on 2020-08-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pervez', '0028_auto_20200825_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='extras',
        ),
    ]
